### PR TITLE
Add bwtester graph and continuous testing

### PR DESCRIPTION
**Pull request by mwfarb**
- Adding bwtester graph for each direction.
- Adding ability for continuous testing by GUI switch.
- Added regex to extract data points and errors from bwtester response.
- Importing local highcharts.com js library for graphing.
- Added master interval input GUI for continuous testing.
- Posting achieved and attempted bandwidth to graph
- Posting errors (in tooltip) along with attempted bandwidth to graph.
- Added real-time movement of live graph data.
- Added hide/show of continuous testing elements based on tab selection.
- Added switch for local/UTC time on graph.
- Importing hacktimer js library to limit browser low-priority
scheduling of graph.
- Added disabling of other tabs when testing is active.
- Configured master bwtester interval to occur +1 second beyond longest
test direction.

Also:
- Adding locahost server parameter loading for testing
- Added visual formatting of new AS numbers.
- Added new static AS server address formats.

### CODE REVIEW

**Comment by mwfarb** [comment]
@perrig  @chaehni This is ready for testing and review. Here is a screen shot:
screenshot from 2018-07-05 13-27-43

**Comment by mwfarb** [comment]
In Chrome, there is a bug where, after continuous testing is switched off again, the tabs are not re-enabled.

**Comment by mwfarb** [comment]
The tooltip over the graph should probably obey the UTC switch, at the moment it's always local time.

**Comment by mwfarb** [comment]
Running a continuous test on Ubuntu, in Firefiox, while running a Hangouts call produced some performance issues. The graph kept running, but the the test seemed to run way too long. The video consumes much bandwidth, but it seems like we should have better notification on the graph somehow.

**Comment by chaehni** [comment]
Sorry for my late feedback. I had some problems getting the bwtester to run after the update.
I had a look at this new feature and it looks great!
Two suggestions:
- The interval for the continuous test should not go below the test duration. Currently, you can set a 1s interval for a test that takes 10s. You can even set it to 0.
- Can you space out the controls of the continuous test a bit? Currently, the buttons and the graph sit really close together. Also, maybe add some space between the lines of  the `Execute Test` button and the `Continuous Bandwidth Test` switch.

**Comment by mwfarb** [comment]
I've had a look about the performance issues when continuous testing is run > 5 minutes or so. Based on that and consulting with a colleague, I think 2 things should change:
1. The graph update drawing intervals need to be throttled down in the JS layer when the tab loses focus, otherwise the `setInterval()` messages for tests and graph ticks stack up. For now the test execution timer can stay in JS as is, and the drawing timer throttle should keep the message queue free to avoid interfering with the test execution timer.
2. The test execution interval timer should move to the Go layer, since the JS timer must ultimately obey the browser's whim to be responsive. This should be done in a separate PR since there are many architectural changes needed to make that happen.

I'll send another commit when issue 1 and the above comments are ready for review again.

**Comment by mwfarb** [comment]
@chaehni I've addressed your comments and worked on performance as noted above.

**Comment by chaehni** [comment]
@mwfarb I ran some longer tests:
When I run the continuous test in the background (browser not in focus) and then come back after ~10min the site is no longer responsive. Sometimes the UI gets restored but the server has to be restarted to make it functional again.

The UI looks good to me. However, I just noticed that the dials behave weird:
- The delete key does not work in the input field
- left/right arrow keys decrease/increase the values instead of navigating the input
- when I delete the bw value completley it gets restored to 0.01 and cannot be changed after that

**Comment by mwfarb** [comment]
@chaehni Thanks for your feedback and testing. As discussed today, I'll work on solution 2 above as well and provide another commit. Hopefully it goes quickly.

**Pull request merged**
