### PR TITLE
Fix SCION address format

### PR DESCRIPTION
**Pull request by FR4NK-W**
Uses the new formatting of 64bit SCION addresses, with : for entry and _ for file system representation
Updates to version in use for SCIONLab

### CODE REVIEW

**Comment by hausheer** [comment]
I receive the following error when trying to start the bwtestserver, even though my node receives beacons:
`2018-07-04T23:38:03.172+0200 [CRIT] Fatal error. Exiting. err="SCION network not initialized"`

**Comment by hausheer** [comment]
the bwtestclient results in the following error (on any platform)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x8c9c87]

goroutine 1 [running]:
github.com/scionproto/scion/go/lib/snet.(*Network).PathResolver(...)
        /home/ubuntu/go/src/github.com/scionproto/scion/go/lib/snet/snet.go:245
github.com/perrig/scionlab/bwtester/bwtestlib.ChoosePath(0x9e0000, 0x0, 0x0, 0x11, 0xffaa0001004c, 0xdf2800, 0xc4210fc9a0, 0x7596, 0x0, 0x0, ...)
        /home/ubuntu/go/src/github.com/perrig/scionlab/bwtester/bwtestlib/bwtestlib.go:330 +0x57
main.main()
        /home/ubuntu/go/src/github.com/perrig/scionlab/bwtester/bwtestclient/bwtestclient.go:315 +0x302f
exit status 2

**Comment by FR4NK-W** [comment]
Interesting, what are the client parameters you are using?

**Comment by FR4NK-W** [comment]
@hausheer 
The "SCION network not initialized" error happens when the sciond socket cannot be found.
When you start SCION, do you have the sdISD-AS.sock socket?

I cannot reproduce the client error. Do you have more details?

**Comment by hausheer** [comment]
@FR4NK-W sciond is running as follows: `/usr/bin/python3 /home/scion/go/src/github.com/scionproto/scion/python/bin/sciond --api-addr /run/shm/sciond/default.sock sd17-ffaa_1_1a gen/ISD17/ASffaa_1_1a/endhost`
Should default.sock be renamed to sd17-ffaa_1_1a.sock?

**Comment by FR4NK-W** [comment]
@hausheer 
The "SCION network not initialized" error happens when the sciond socket cannot be found.
When you start SCION, do you have the sdISD-AS.sock socket?

I cannot reproduce the client error. Do you have more details?
The error seems to happen during the initialization of the PathResolver, which is not specific to the bwtester.
Did you build the bwtester against the right SCION version, the one from scionlab?

**Comment by FR4NK-W** [comment]
^ Yes the sciond socket should be sd17-ffaa_1_1a.sock

**Comment by hausheer** [comment]
Hmm, I am using the default configuration from SCIONLab and here it creates a default.sock instead. Oddly, showpaths works without any issues.

**Comment by hausheer** [comment]
It appears that prior to the remapping the supervisord.conf in the gen folder looked like this:
`command = bash -c 'exec "python/bin/sciond" "--api-addr" "/run/shm/sciond/sd1-1026.sock" "sd1-1026" "gen/ISD1/AS1026/endhost" &>logs/sd1-1026.OUT'`
now it looks like this:
`command = bash -c 'exec "python/bin/sciond" "--api-addr" "/run/shm/sciond/default.sock" "sd17-ffaa_1_1a" "gen/ISD17/ASffaa_1_1a/endhost"&>logs/sd17-ffaa_1_1a.OUT'`

**Pull request merged**
